CREATE TABLE season (
    seasonentryid INT PRIMARY KEY,
    team_id INT,
    title VARCHAR(100),
    year INT,
    h_a CHAR(1),
    xG FLOAT,
    xGA FLOAT,
    npxG FLOAT,
    npxGA FLOAT,
    deep INT,
    deep_allowed INT,
    scored INT,
    missed INT,
    xpts FLOAT,
    result VARCHAR(10),
    date DATETIME,
    wins INT,
    draws INT,
    loses INT,
    pts INT,
    npxGD FLOAT,
    ppda_att INT,
    ppda_def INT,
    ppda_allowed_att INT,
    ppda_allowed_def INT,
    FOREIGN KEY (team_id) REFERENCES teams(team_id)
);
